sudo: false
language: go
go:
  - 1.11.x
cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod
install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
script:
  - golangci-lint run ./...
  - go test       ./...
  - go test -race ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)