sudo: false
language: go
go:
  - 1.11.x
services:
- redis-server
cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod
install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env
script:
  - redis-cli info server
  - go test -tags integration      ./...
  - go test -tags integration -race ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
